In [ ]:
import numpy as np

In [ ]:
array_2x2 = np.array([[1, 2], [3, 4]])
print("2x2 Array:\n", array_2x2)

2x2 Array:
 [[1 2]
 [3 4]]


In [ ]:
random_3x4 = np.random.rand(3, 4)
print("Random 3x4 Array:\n", random_3x4)

Random 3x4 Array:
 [[0.7750197  0.05397887 0.45028824 0.80537031]
 [0.51280367 0.53290259 0.24312458 0.30335562]
 [0.12776    0.09572804 0.98659491 0.55520052]]


In [ ]:
ones_array = np.ones((2, 3))
zeroes_array = np.zeros((2, 3))
print("Array of Ones:\n", ones_array)
print("Array of Zeroes:\n", zeroes_array)

Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of Zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
random_6x3 = np.random.rand(6, 3)
transposed_3x6 = random_6x3.T
print("Random 6x3 Array:\n", random_6x3)
print("Transposed Array (3x6):\n", transposed_3x6)

Random 6x3 Array:
 [[0.23574034 0.55598533 0.27528347]
 [0.65869174 0.79136591 0.02892175]
 [0.91851939 0.66852341 0.90887347]
 [0.05098784 0.40514678 0.14916944]
 [0.24794473 0.23648913 0.64328657]
 [0.38184204 0.72370748 0.61282656]]
Transposed Array (3x6):
 [[0.23574034 0.65869174 0.91851939 0.05098784 0.24794473 0.38184204]
 [0.55598533 0.79136591 0.66852341 0.40514678 0.23648913 0.72370748]
 [0.27528347 0.02892175 0.90887347 0.14916944 0.64328657 0.61282656]]


In [ ]:
n, p, m = 2, 3, 4
array_nxp = np.random.rand(n, p)
array_pxm = np.random.rand(p, m)
dot_product = np.dot(array_nxp, array_pxm)
print("Array n x p:\n", array_nxp)
print("Array p x m:\n", array_pxm)
print("Dot Product (n x m):\n", dot_product)

Array n x p:
 [[0.6947611  0.80020715 0.90568878]
 [0.55175707 0.78430183 0.54031986]]
Array p x m:
 [[0.07450585 0.95696387 0.93674535 0.44359106]
 [0.80534912 0.00124058 0.29585939 0.3015116 ]
 [0.59450385 0.23838725 0.09272196 0.72913093]]
Dot Product (n x m):
 [[1.23464536 0.88175866 0.97154028 1.20982726]
 [0.99396816 0.65778994 0.79899845 0.87519453]]
